reports/urls.py
from django.urls import path
from .views import create_report_view, ReportListView, ReportDetailView,UploadReportView, render_pdf_view, csv_upload_view

app_name = 'reports'

urlpatterns = [
    path('', ReportListView.as_view(), name = 'main'),
    path('save/', create_report_view, name = 'create-report'),
    path('from_file/', UploadReportView.as_view(), name = 'from-file'),
    path('upload/',csv_upload_view, name = 'upload'),
    path('<pk>/', ReportDetailView.as_view(), name = 'detail'),
    path('<pk>/pdf/', render_pdf_view, name = 'pdf'),
]

reports_proj/urls.py
from reports_proj.settings import ADMIN_URL
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import login_view, logout_view, register_view
from ajax_select import urls as ajax_select_urls

urlpatterns = [
    path(ADMIN_URL, admin.site.urls),
    path('', include('sales.urls', namespace='sales')),
    path('reports/', include('reports.urls', namespace='reports')),
    path('my_profile/', include('profiles.urls', namespace='profiles')),
    path('login/', login_view, name = "login"),
    path('logout/', logout_view, name = "logout"),
    path('register/', register_view, name = "register"),
    path(r'^ajax_select', include(ajax_select_urls)),
]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATICFILES_DIRS)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

sales/urls.py
from django.urls import path
from .views import home_view, SaleListView, SaleDetailView

app_name = 'sales'

urlpatterns = [
    path('', home_view, name = 'home'),
    path('sales/', SaleListView.as_view(), name = 'list'),
    path('sales/<pk>', SaleDetailView.as_view(), name = 'detail'),
]

reports/models.py
from django.db import models
from profiles.models import Profile
from django.shortcuts import reverse

# Create your models here.

class Report(models.Model):
    name = models.CharField(max_length=120)
    image = models.ImageField(upload_to='reports', blank=True)
    remarks = models.TextField()
    author = models.ForeignKey(Profile, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    class Meta:
        verbose_name = ("Report")
        verbose_name_plural = ("Reports")
        ordering = ("-created",)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("reports:detail", kwargs={"pk": self.pk})
    

reports/forms.py
from django import forms
from .models import Report


class ReportForm(forms.ModelForm):
    class Meta:
        model = Report
        fields = ('name', 'remarks')

reports/views.py
import pandas as pd
import datetime
from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, DetailView, TemplateView
from django.conf import settings
from django.http import HttpResponse
from django.template.loader import get_template
from xhtml2pdf import pisa
from django.utils.dateparse import parse_date
from products.models import Product
from customers.models import Customer
from profiles.models import Profile
from sales.models import Position, Sale
from .utils import get_report_image
from .models import Report
from .forms import ReportForm
from sales.models import CSV
from profiles.models import Profile
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.
class ReportListView(LoginRequiredMixin,ListView):
    model=Report
    template_name="reports/main.html"


class ReportDetailView(LoginRequiredMixin,DetailView):
    model=Report
    template_name="reports/detail.html"

class UploadReportView(LoginRequiredMixin,TemplateView):
    template_name = "reports/from_file.html"


@login_required
def create_report_view(request):
    form = ReportForm(request.POST or None)
    if  request.headers.get('x-requested-with') == 'XMLHttpRequest':
        image = request.POST.get("image")

        current_user = auth.get_user(request)
        image = get_report_image(image)
        author = Profile.objects.get(user = current_user)

        if form.is_valid():
            instance = form.save(commit=False)
            instance.image = image
            instance.author = author
            instance.save()

        return JsonResponse({"msg":"success"})
    return JsonResponse({})

@login_required
def render_pdf_view(request, pk):
    template_path = 'reports/pdf.html'
    obj = get_object_or_404(Report, pk=pk)
    context = {'obj': obj}
    # Create a Django response object, and specify content_type as pdf
    response = HttpResponse(content_type='application/pdf')
    #if Download
    # response['Content-Disposition'] = 'attachment; filename="report.pdf"'
    # if Display
    response['Content-Disposition'] = 'filename="report.pdf"'
    # find the template and render it.
    template = get_template(template_path)
    html = template.render(context)

    # create a pdf
    pisa_status = pisa.CreatePDF(
       html, dest=response)
    # if error then show some funny view
    if pisa_status.err:
       return HttpResponse('We had some errors <pre>' + html + '</pre>')
    return response

@login_required
def csv_upload_view(request):
    if request.method == 'POST':
        csv_files_name = request.FILES.get('file').name
        csv_files = request.FILES.get('file')
        obj, created = CSV.objects.get_or_create(file_name = csv_files_name)

        if created:
            obj.csv_file = csv_files
            obj.save()
            csv_df = pd.read_csv(obj.csv_file.path)
            current_user = auth.get_user(request)
            for index, row in  csv_df.iterrows():
                data = list(row)

                transaction_id = data[1]
                product = data[2]
                quantity = int(data[3])
                customer = data[4]
                date = datetime.datetime.strptime(data[5], "%d-%m-%Y").date()
                
                print(date)

                try:
                    product_obj = Product.objects.get(name__iexact = product)
                except:
                    product_obj = None
                
                if product_obj is not None:
                    customer_obj, _ = Customer.objects.get_or_create(name=customer)
                    salesman_obj = Profile.objects.get(user=current_user)
                    position_obj= Position.objects.create(product=product_obj, quantity=quantity, created=date)
                    print(position_obj)
                    sale_obj, _ = Sale.objects.get_or_create(transaction_id=transaction_id, salesman=salesman_obj, customer=customer_obj, created=date)
                    sale_obj.position.add(position_obj)
                    sale_obj.save()
            return JsonResponse({"ex":False})

        print(obj.csv_file.path)
    return JsonResponse({"ex":True})

reports/templates/reports/detail.html
{% extends 'base.html' %}

{% block title %}
    {{object.name}}
{% endblock title %}

{% block content %}
    {% if object.image %}
        <img src = "{{object.image.url}}" class = "img-fluid mb-2" alt = "{{object.name}}">
    {% endif %}
    <br>
    <h3>Remarks</h3>
    <p>{{object.remarks}}</p>
    <hr>
    <p>Author: <b>{{object.author.user.username}}</b></p>
    <p>Created: <b>{{object.created}}</b></p>
    <hr>

{% endblock content %}

reports/templates/reports/from_file.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Upload sales document
{% endblock title %}

{% block scripts %}
    <script src = "{% static 'reports/upload.js' %}" defer></script>
{% endblock scripts %}

{% block content %}
<h5>Upload Sales document</h5>
<br>
<div id = "alert-box"></div>
<form class="dropzone dz" id="my-dropzone">
    {% csrf_token %}
    <div class = "fallback">
        <input type="file" name="file" multiple/>
    </div>
</form>

{% endblock content %}

reports/templates/reports/main.html
{% extends 'base.html' %}

{% block title %}
    reports
{% endblock title %}

{% block content %}
Reports
<hr>
{% for obj in  object_list%}
    <div class="card mb-3">
        {% if obj.image %}
            <img src="{{obj.image.url}}" class="card-img-top" alt="{{obj.name}}">
        {% endif %}
        <div class="card-body">
            <h5 class="card-title">{{obj.name}}</h5>
            <p class="card-text">{{obj.remarks|truncatewords:2}}</p>
            <a href="{{obj.get_absolute_url}}" class="btn btn-primary">details</a>
            <a href="{% url 'reports:pdf' obj.pk %}" class="btn btn-primary">pdf</a>
        </div>
    </div>
{% endfor %}
{% endblock content %}

reports/templates/reports/pdf.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title></title>
    <style>
        .image {
            width:100%;
            height:auto;
        }
    </style>
</head>
<body>
    <h1>{{obj.name}}</h1>
    <hr>
    {% if obj.image %}
        <img src = "{{obj.image.path}}" class = "image">
    {% endif %}
    <br>
    <h3>Remarks</h3>
    <p>{{obj.remarks}}</p>
    <hr>
    <p>Author: <b>{{obj.author.user.username}}</b></p>
    <p>Created: <b>{{obj.created}}</b></p>
</body>
</html